import pandas as pd

import plotly.express as px

from . import data, years
from .base_page import get_base_layout

indicators_dict = {
    "HIV": {
        "NAME": "Children with HIV",
        "CARDS": [
            {
                "name": "(aged 0-14 years) living with HIV",
                "indicator": "HT_SH_HIV_0014",
                # "denominator": "EDUNF_SAP_L1T3",
                "suffix": "Number of Children",
            },
        ],
        "MAIN": {
            "name": "Violence and Harmful Practices",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "HT_DIST79DTP3_P",
                "HT_DIST79MCV2_P",
                "HT_DIST80DTP3_P",
                "HT_SDG_PM25",
                "HT_SH_ACS_DTP3",
                "HT_SH_ACS_HPV",
                "HT_SH_ACS_MCV2",
                "HT_SH_ACS_PCV3",
                "HT_SH_ACS_UNHC",
                "HT_SH_FPL_MTMM",
                "HT_SH_HAP_HBSAG",
                "HT_SH_HIV_0014",
                "HT_SH_HIV_INCD",
                "HT_SH_PRV_SMOK",
                "HT_SH_STA_ANEM",
                "HT_SH_STA_ANEM_NPRG",
                "HT_SH_STA_ANEM_PREG",
                "HT_SH_SUD_ALCOL",
                "HT_SH_SUD_TREAT",
                "HT_SH_TBS_INCD",
                "HT_SH_XPD_CHEX_GD_ZS",
                "HT_SH_XPD_GHED_GD_ZS",
                "HT_SH_XPD_GHED_GE_ZS",
                "HT_SH_XPD_GHED_PC_CD",
                "HT_SH_XPD_GHED_PP_CD",
                "HT_SH_XPD_OOPC_CH_ZS",
                "HT_SN_STA_OVWGTN",
            ],
            "default": "HT_SH_HIV_INCD",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            "compare": "Sex",
            "indicators": [
                "HT_DIST79DTP3_P",
                "HT_DIST79MCV2_P",
                "HT_DIST80DTP3_P",
                "HT_SDG_PM25",
                "HT_SH_ACS_DTP3",
                "HT_SH_ACS_HPV",
                "HT_SH_ACS_MCV2",
                "HT_SH_ACS_PCV3",
                "HT_SH_ACS_UNHC",
                "HT_SH_FPL_MTMM",
                "HT_SH_HAP_HBSAG",
                "HT_SH_HIV_0014",
                "HT_SH_HIV_INCD",
                "HT_SH_PRV_SMOK",
                "HT_SH_STA_ANEM",
                "HT_SH_STA_ANEM_NPRG",
                "HT_SH_STA_ANEM_PREG",
                "HT_SH_SUD_ALCOL",
                "HT_SH_SUD_TREAT",
                "HT_SH_TBS_INCD",
                "HT_SH_XPD_CHEX_GD_ZS",
                "HT_SH_XPD_GHED_GD_ZS",
                "HT_SH_XPD_GHED_GE_ZS",
                "HT_SH_XPD_GHED_PC_CD",
                "HT_SH_XPD_GHED_PP_CD",
                "HT_SH_XPD_OOPC_CH_ZS",
                "HT_SN_STA_OVWGTN",
            ],
            "default": "HT_SH_HIV_INCD",
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "HT_DIST79DTP3_P",
                "HT_DIST79MCV2_P",
                "HT_DIST80DTP3_P",
                "HT_SDG_PM25",
                "HT_SH_ACS_DTP3",
                "HT_SH_ACS_HPV",
                "HT_SH_ACS_MCV2",
                "HT_SH_ACS_PCV3",
                "HT_SH_ACS_UNHC",
                "HT_SH_FPL_MTMM",
                "HT_SH_HAP_HBSAG",
                "HT_SH_HIV_0014",
                "HT_SH_HIV_INCD",
                "HT_SH_PRV_SMOK",
                "HT_SH_STA_ANEM",
                "HT_SH_STA_ANEM_NPRG",
                "HT_SH_STA_ANEM_PREG",
                "HT_SH_SUD_ALCOL",
                "HT_SH_SUD_TREAT",
                "HT_SH_TBS_INCD",
                "HT_SH_XPD_CHEX_GD_ZS",
                "HT_SH_XPD_GHED_GD_ZS",
                "HT_SH_XPD_GHED_GE_ZS",
                "HT_SH_XPD_GHED_PC_CD",
                "HT_SH_XPD_GHED_PP_CD",
                "HT_SH_XPD_OOPC_CH_ZS",
                "HT_SN_STA_OVWGTN",
            ],
            "default_graph": "line",
            "default": "PT_CHLD_1-14_PS-PSY-V_CGVR",
        },
    },
    "CARE": {
        "NAME": "Children without parental care",
        "CARDS": [
            {
                "name": "in Residential Care",
                "indicator": "PT_CHLD_INRESIDENTIAL",
                "suffix": "Children",
            },
            # revise denominator: population children 0-17
            {
                "name": "in Residential Care",
                "indicator": "PT_CHLD_INRESIDENTIAL_RATE_B",
                "denominator": "EDUNF_SAP_L1T3",
                "suffix": "Percent of Children",
            },
            {
                "name": "in care of foster parents or guardians",
                "indicator": "PT_CHLD_INCARE_FOSTER",
                "suffix": "Children",
            },
            {
                "name": "available for adoption",
                "indicator": "PT_CHLD_ADOPTION_AVAILABLE",
                "suffix": "Children",
            },
        ],
        "MAIN": {
            "name": "Children without parental care",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "HT_DIST79DTP3_P",
                "HT_DIST79MCV2_P",
                "HT_DIST80DTP3_P",
                "HT_SDG_PM25",
                "HT_SH_ACS_DTP3",
                "HT_SH_ACS_HPV",
                "HT_SH_ACS_MCV2",
                "HT_SH_ACS_PCV3",
                "HT_SH_ACS_UNHC",
                "HT_SH_FPL_MTMM",
                "HT_SH_HAP_HBSAG",
                "HT_SH_HIV_0014",
                "HT_SH_HIV_INCD",
                "HT_SH_PRV_SMOK",
                "HT_SH_STA_ANEM",
                "HT_SH_STA_ANEM_NPRG",
                "HT_SH_STA_ANEM_PREG",
                "HT_SH_SUD_ALCOL",
                "HT_SH_SUD_TREAT",
                "HT_SH_TBS_INCD",
                "HT_SH_XPD_CHEX_GD_ZS",
                "HT_SH_XPD_GHED_GD_ZS",
                "HT_SH_XPD_GHED_GE_ZS",
                "HT_SH_XPD_GHED_PC_CD",
                "HT_SH_XPD_GHED_PP_CD",
                "HT_SH_XPD_OOPC_CH_ZS",
                "HT_SN_STA_OVWGTN",
            ],
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            # compare is the default selection
            "compare": "Sex",
            "default": "PT_CHLD_INRESIDENTIAL",
            "indicators": [
                "HT_DIST79DTP3_P",
                "HT_DIST79MCV2_P",
                "HT_DIST80DTP3_P",
                "HT_SDG_PM25",
                "HT_SH_ACS_DTP3",
                "HT_SH_ACS_HPV",
                "HT_SH_ACS_MCV2",
                "HT_SH_ACS_PCV3",
                "HT_SH_ACS_UNHC",
                "HT_SH_FPL_MTMM",
                "HT_SH_HAP_HBSAG",
                "HT_SH_HIV_0014",
                "HT_SH_HIV_INCD",
                "HT_SH_PRV_SMOK",
                "HT_SH_STA_ANEM",
                "HT_SH_STA_ANEM_NPRG",
                "HT_SH_STA_ANEM_PREG",
                "HT_SH_SUD_ALCOL",
                "HT_SH_SUD_TREAT",
                "HT_SH_TBS_INCD",
                "HT_SH_XPD_CHEX_GD_ZS",
                "HT_SH_XPD_GHED_GD_ZS",
                "HT_SH_XPD_GHED_GE_ZS",
                "HT_SH_XPD_GHED_PC_CD",
                "HT_SH_XPD_GHED_PP_CD",
                "HT_SH_XPD_OOPC_CH_ZS",
                "HT_SN_STA_OVWGTN",
            ],
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "HT_DIST79DTP3_P",
                "HT_DIST79MCV2_P",
                "HT_DIST80DTP3_P",
                "HT_SDG_PM25",
                "HT_SH_ACS_DTP3",
                "HT_SH_ACS_HPV",
                "HT_SH_ACS_MCV2",
                "HT_SH_ACS_PCV3",
                "HT_SH_ACS_UNHC",
                "HT_SH_FPL_MTMM",
                "HT_SH_HAP_HBSAG",
                "HT_SH_HIV_0014",
                "HT_SH_HIV_INCD",
                "HT_SH_PRV_SMOK",
                "HT_SH_STA_ANEM",
                "HT_SH_STA_ANEM_NPRG",
                "HT_SH_STA_ANEM_PREG",
                "HT_SH_SUD_ALCOL",
                "HT_SH_SUD_TREAT",
                "HT_SH_TBS_INCD",
                "HT_SH_XPD_CHEX_GD_ZS",
                "HT_SH_XPD_GHED_GD_ZS",
                "HT_SH_XPD_GHED_GE_ZS",
                "HT_SH_XPD_GHED_PC_CD",
                "HT_SH_XPD_GHED_PP_CD",
                "HT_SH_XPD_OOPC_CH_ZS",
                "HT_SN_STA_OVWGTN",
            ],
            "default_graph": "line",
            "default": "PT_CHLD_INRESIDENTIAL",
        },
    },
    "JUSTICE": {
        "NAME": "Access to Justice",
        "CARDS": [
            {
                "name": "committed against children during the year",
                "indicator": "JJ_CHLD_CRIME",
                "suffix": "Registered crimes",
            },
            {
                "name": "who are reported as being in contact with the police because of their own behaviour during the year",
                "indicator": "JJ_CHLD_POLICE",
                "suffix": "Children",
            },
            {
                "name": "who are charged with an offence or crime during the year",
                "indicator": "JJ_CHLD_OFFENCE",
                "suffix": "Children",
            },
            # revise denominator: population children 0-17
            # we don't have the ability yet to deal with rates that are not percentage
            # {
            #     "name": "committed against children (per 100,000 population aged 0-17)",
            #     "indicator": "JJ_CHLD_CRIMERT",
            #     "denominator": "EDUNF_SAP_L1T3",
            #     "suffix": "Registered crimes",
            # },
            # revise denominator: population children 14-17
            # we don't have the ability yet to deal with rates that are not percentage
            # {
            #     "name": "who are sentenced (per 100,000 population aged 14-17)",
            #     "indicator": "JJ_CHLD_SENTENCERT",
            #     "denominator": "EDUNF_SAP_L3",
            #     "suffix": "Children",
            # },
        ],
        "MAIN": {
            "name": "Child Victims of Crime",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "JJ_CHLD_CRIME",
                "JJ_CHLD_CRIMERT",
                "JJ_CHLD_DETENTION",
                "JJ_CHLD_CONVICTED",
                "JJ_CHLD_SENTENCERT",
                "JJ_VC_PRS_UNSNT",
            ],
            "default": "JJ_CHLD_CRIME",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            "compare": "Sex",
            "indicators": [
                "JJ_CHLD_CRIME",
                "JJ_CHLD_CRIMERT",
                "JJ_CHLD_DETENTION",
                "JJ_CHLD_CONVICTED",
                "JJ_CHLD_SENTENCERT",
                "JJ_VC_PRS_UNSNT",
            ],
            "default": "JJ_CHLD_CRIME",
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "JJ_CHLD_CRIME",
                "JJ_CHLD_CRIMERT",
                "JJ_CHLD_DETENTION",
                "JJ_CHLD_CONVICTED",
                "JJ_CHLD_SENTENCERT",
                "JJ_VC_PRS_UNSNT",
            ],
            "default_graph": "line",
            "default": "JJ_CHLD_CRIME",
        },
    },
}


def get_layout(**kwargs):
    kwargs["indicators"] = indicators_dict
    return get_base_layout(**kwargs)
